
com.opengamma.strata.product.fx.type.FxSwapConvention:
  - of:
      signature: "FxSwapConvention of(String)"

com.opengamma.strata.product.fx.type.FxSwapTemplate:
  - build
  - of:
      signature: "FxSwapTemplate of(Period, FxSwapConvention)"
