
com.opengamma.strata.basics.index.FloatingRateIndex:
  - parse:
      signature: "FloatingRateIndex parse(String)"

  - parseWithTenor:
      method: parse
      signature: "FloatingRateIndex parse(String, Tenor)"

com.opengamma.strata.basics.index.FxIndex:
  - of:
      signature: "FxIndex of(String)"

com.opengamma.strata.basics.index.IborIndex:
  - of

com.opengamma.strata.basics.index.Index:

com.opengamma.strata.basics.index.OvernightIndex:
  - of

com.opengamma.strata.basics.index.PriceIndex:
  - of
